### ISSUE TITLE
启动不成功，能帮忙也看下吗？

### ISSUE THREAD

**Issue by lixsyulin** [leinue/vue-feeds#2]
0 info it worked if it ends with ok
1 verbose cli [ 'D:\Program Files\nodejs\\node.exe',
1 verbose cli   'D:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@2.10.1
3 info using node@v0.12.4
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info predev vue-seeds-master@1.0.0
6 info dev vue-seeds-master@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info vue-seeds-master@1.0.0 Failed to exec dev script
9 verbose stack Error: vue-seeds-master@1.0.0 dev: `webpack-dev-server --inline --hot --quiet`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (D:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (D:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid vue-seeds-master@1.0.0
11 verbose cwd F:\TDDownload\vue\vue-seeds-master\vue-seeds-master
12 error Windows_NT 6.1.7601
13 error argv "D:\Program Files\nodejs\\node.exe" "D:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "dev"
14 error node v0.12.4
15 error npm  v2.10.1
16 error code ELIFECYCLE
17 error vue-seeds-master@1.0.0 dev: `webpack-dev-server --inline --hot --quiet`
17 error Exit status 1
18 error Failed at the vue-seeds-master@1.0.0 dev script 'webpack-dev-server --inline --hot --quiet'.
18 error This is most likely a problem with the vue-seeds-master package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     webpack-dev-server --inline --hot --quiet
18 error You can get their info via:
18 error     npm owner ls vue-seeds-master
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by lixsyulin** [comment]
![image](https://cloud.githubusercontent.com/assets/1774656/12079616/c6e0c236-b27a-11e5-9a88-95f7faf9f637.png)

**Comment by leinue** [comment]
我用mac osx开发的，估计和windows不兼容，我也暂时无法解决，抱歉

**Comment by leinue** [comment]
vim package.json
找到babel-runtime
修改后面的版本号为^5.8.0
然后执行npm install
再执行 npm run dev即可
